# Generated by Django 5.1.5 on 2025-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
