# Generated by Django 5.1.5 on 2025-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_claim_amount_claim_claim_date_claim_claim_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reason',
            field=models.CharField(default='DEFAULT_REASON', max_length=255),
        ),
    ]
